### Package Imports

In [20]:
import numpy as np

# Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension (I just learned about comprehensions in an awesome course by Maven) into an array?

Once you've done that report the following about the array:
* The number of dimensions 
* The shape
* The number of elements in the array
* The type of data contained inside

In [21]:
my_list = [x * 10 for x in range(1, 11)] ##already given for the reference

my_list_array = np.array(my_list)

my_list_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [22]:
print(f"ndim: {my_list_array.ndim}")
print(f"shape: {my_list_array.shape}")
print(f"size : {my_list_array.size}")
print(f"dtype : {my_list_array.dtype}")

ndim: 1
shape: (10,)
size : 10
dtype : int32


# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays. 

Does NumPy have anything like the range() function from base Python?

If so: 
* create the same array from assignment 1 using a NumPy function. 
* Make it 5 rows and 2 columns. 
* It's ok if the datatype is float or int.

In [23]:
np.linspace(10,100,10).reshape(5,2)

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

Looking good so far! One of our data scientists asked about random number generation in NumPy.

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called `random_array`.

# Assignment 3: Accessing Array Data


Slice and index the `random_array` we created in the previous exercise. Perform the following:

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second selement of the third row.

Thanks!


In [24]:
random_array

NameError: name 'random_array' is not defined

In [ ]:
random_array[:2,]

In [ ]:
random_array[:,:1]

In [ ]:
random_array[2,1]

# Assignment 4: Arithmetic Operations

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [ ]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

total = prices + 5

total

In [ ]:
discount_pct = random_array[:2, :].reshape(6)

pct_owed = 1 - discount_pct

final_owed = total * pct_owed

final_owed.round(2)

In [ ]:
((1- (random_array[:2, :].reshape(6)))*total).round(2)

In [ ]:
print(discount_pct)
print(pct_owed)
print(final_owed)

#  Assignment 5: Filtering Arrays

Filter the product array to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25. 
Store the elements returned in an array called `fancy_feast_special`.

Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not. 

In [ ]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

products #already given as a reference

In [ ]:
products[prices > 25]

In [ ]:
mask = (prices > 25) | (products == 'cola')

fancy_feast_special = products[mask]

fancy_feast_special

In [ ]:
Shipping_cost = np.where(prices > 20, 0, 5)

Shipping_cost

# Assignment 6: Aggregating and Sorting Arrays

First, grab the top 3 highest priced items in our list. 

Then, calculated the mean, min, max, and median of the top three prices.

Finally, calculate the number of unique price tiers in our `price_tiers` array.

In [ ]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99]) #already given for the reference

prices.sort()

In [ ]:
prices

In [ ]:
top_3 = prices[-3:]

In [ ]:
print(f"Mean: {top_3.mean()}")
print(f"Min: {top_3.min()}")
print(f"Max: {top_3.max()}")
print(f"Median: {np.median(top_3)}")

In [ ]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"]) #already given for the reference

In [ ]:
np.unique(price_tiers)

# Assignment 7: Bringing it All Together

Ok, final NumPy task - let's read in some data with the help of Pandas.

Our data scientist provided the code to read in a csv as a Pandas dataframe, and has converted the two columns of interest to arrays.

* Filter `sales_array` down to only sales where the product family was produce. 

* Then, randomly sample roughly half (random number < .5) of the produce sales and report the mean and median sales. Use a random seed of 2022.

* Finally, create a new array that has the values 'above_both', 'above_median', and 'below_both' based on whether the sales were above the median and mean of the sample, just above the median of the sample, or below both the median and mean of the sample. 

In [26]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    "../retail/retail_2016_2017.csv", skiprows=range(1, 11000), nrows=1000
)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])

In [28]:
#first filter the array

produce_array = sales_array[family_array == 'PRODUCE']

produce_array #use produce_array.size to know the size of the array

array([1662.394,  447.064, 2423.944,  962.866, 1236.404,  298.441,
       1077.44 , 3404.531,  962.96 ,  279.505, 1852.786, 1089.319,
        726.516, 7860.031,  446.038, 1155.385,  120.202,  862.092,
        473.952,  254.263, 1272.755, 2775.771, 2030.762, 1657.432,
       2339.906,  722.333, 1567.843, 2458.456,  673.885, 8834.15 ])

In [37]:
#generate random array less than 30
from numpy.random import default_rng

rng = np.random.default_rng(2022)

random_array = rng.random(30)

produce_sample = produce_array[random_array < 0.5]

produce_sample

array([1662.394,  447.064,  962.866, 1077.44 , 3404.531,  962.96 ,
       1089.319, 7860.031,  446.038, 1272.755, 2775.771, 2339.906,
        722.333, 1567.843, 2458.456,  673.885, 8834.15 ])

In [35]:
#mean of sales

mean_of_sales = produce_sample.mean()

mean_of_sales

2268.102470588235

In [36]:
#median of sales
median_of_sales = np.median(produce_sample)

median_of_sales

1272.755

In [38]:
np.where(
     produce_sample < median_of_sales,
     "below_both",
     np.where(produce_sample > mean_of_sales, "above_both", "above_median")    
)

array(['above_median', 'below_both', 'below_both', 'below_both',
       'above_both', 'below_both', 'below_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'below_both',
       'above_both'], dtype='<U12')